using EasyAzure.Core.Interfaces;
using EasyAzure.Core.Models;
using Microsoft.Extensions.Logging;

namespace EasyAzure.IaC.Services;

/// <summary>
/// Generates Bicep templates from a design environment's canvas nodes.
/// Uses Azure Verified Modules (AVM) module references where available.
///
/// AVM reference: https://azure.github.io/Azure-Verified-Modules/
/// Bicep reference: https://learn.microsoft.com/azure/azure-resource-manager/bicep/
/// </summary>
public class BicepGeneratorService : IBicepGeneratorService
{
    private readonly IDesignerService _designer;
    private readonly ILogger<BicepGeneratorService> _logger;

    public BicepGeneratorService(IDesignerService designer, ILogger<BicepGeneratorService> logger)
    {
        _designer = designer;
        _logger = logger;
    }

    public async Task<GenerateBicepResult> GenerateBicepAsync(string environmentId, CancellationToken ct = default)
    {
        var env = await _designer.GetEnvironmentAsync(environmentId, ct);
        if (env is null)
        {
            return new GenerateBicepResult { Bicep = "// Environment not found", Warnings = ["Environment not found."] };
        }

        _logger.LogInformation("Generating Bicep for environment {Id} '{Name}'", env.Id, env.Name);

        var warnings = new List<string>();
        var sb = new System.Text.StringBuilder();

        sb.AppendLine("// Generated by EasyAzure on " + DateTimeOffset.UtcNow.ToString("O"));
        sb.AppendLine("// Environment: " + env.Name);
        sb.AppendLine("// DO NOT EDIT MANUALLY — regenerate from EasyAzure designer");
        sb.AppendLine();
        sb.AppendLine("targetScope = 'resourceGroup'");
        sb.AppendLine();
        sb.AppendLine("@description('Azure region for all resources.')");
        sb.AppendLine("param location string = resourceGroup().location");
        sb.AppendLine();
        sb.AppendLine("@description('Environment tag value.')");
        sb.AppendLine("param environmentName string = 'dev'");
        sb.AppendLine();
        sb.AppendLine("var tags = { environment: environmentName, managedBy: 'easyazure' }");
        sb.AppendLine();

        foreach (var node in env.Nodes)
        {
            var bicep = GenerateNodeBicep(node, warnings);
            sb.AppendLine(bicep);
        }

        return new GenerateBicepResult
        {
            Bicep = sb.ToString(),
            Warnings = warnings,
        };
    }

    private static string GenerateNodeBicep(DesignNode node, List<string> warnings)
    {
        var safeName = SanitizeName(node.Label);
        return node.BlockType switch
        {
            "VNet" => GenerateVNet(safeName, node),
            "Subnet" => GenerateSubnet(safeName, node),
            "NSG" => GenerateNsg(safeName, node),
            "Route Table" => GenerateRouteTable(safeName, node),
            "Key Vault" => GenerateKeyVault(safeName, node),
            "Storage Account" => GenerateStorageAccount(safeName, node),
            "VM" => GenerateVm(safeName, node, warnings),
            "App Service" => GenerateAppService(safeName, node),
            "Private Endpoint" => GeneratePrivateEndpoint(safeName, node),
            _ => $"// Block type '{node.BlockType}' ('{node.Label}') — manual configuration required",
        };
    }

    private static string GenerateVNet(string name, DesignNode node)
    {
        var addressPrefix = GetProp(node, "addressPrefix", "10.0.0.0/16");
        return $$"""
// VNet: {{node.Label}}
// AVM module: br/public:avm/res/network/virtual-network:0.4.0
resource vnet_{{name}} 'Microsoft.Network/virtualNetworks@2024-01-01' = {
  name: '{{name}}'
  location: location
  tags: tags
  properties: {
    addressSpace: {
      addressPrefixes: ['{{addressPrefix}}']
    }
  }
}

""";
    }

    private static string GenerateSubnet(string name, DesignNode node)
    {
        var prefix = GetProp(node, "addressPrefix", "10.0.0.0/24");
        return $$"""
// Subnet: {{node.Label}}
// Parent VNet must be referenced explicitly
resource subnet_{{name}} 'Microsoft.Network/virtualNetworks/subnets@2024-01-01' = {
  name: '{{name}}'
  parent: /* TODO: reference parent VNet */
  properties: {
    addressPrefix: '{{prefix}}'
  }
}

""";
    }

    private static string GenerateNsg(string name, DesignNode node) =>
        $$"""
// NSG: {{node.Label}}
// AVM module: br/public:avm/res/network/network-security-group:0.3.0
resource nsg_{{name}} 'Microsoft.Network/networkSecurityGroups@2024-01-01' = {
  name: 'nsg-{{name}}'
  location: location
  tags: tags
  properties: {
    securityRules: []  // TODO: add rules
  }
}

""";

    private static string GenerateRouteTable(string name, DesignNode node) =>
        $$"""
// Route Table: {{node.Label}}
resource rt_{{name}} 'Microsoft.Network/routeTables@2024-01-01' = {
  name: 'rt-{{name}}'
  location: location
  tags: tags
  properties: {
    routes: []  // TODO: add UDRs
    disableBgpRoutePropagation: false
  }
}

""";

    private static string GenerateKeyVault(string name, DesignNode node) =>
        $$"""
// Key Vault: {{node.Label}}
// AVM module: br/public:avm/res/key-vault/vault:0.9.0
resource kv_{{name}} 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: 'kv-{{name}}'
  location: location
  tags: tags
  properties: {
    tenantId: subscription().tenantId
    sku: { family: 'A', name: 'standard' }
    enableRbacAuthorization: true
    enableSoftDelete: true
    softDeleteRetentionInDays: 90
    enablePurgeProtection: true
    publicNetworkAccess: 'Disabled'
  }
}

""";

    private static string GenerateStorageAccount(string name, DesignNode node) =>
        $$"""
// Storage Account: {{node.Label}}
// AVM module: br/public:avm/res/storage/storage-account:0.14.0
resource sa_{{name}} 'Microsoft.Storage/storageAccounts@2023-05-01' = {
  name: 'st{{name}}'
  location: location
  kind: 'StorageV2'
  tags: tags
  sku: { name: 'Standard_ZRS' }
  properties: {
    supportsHttpsTrafficOnly: true
    minimumTlsVersion: 'TLS1_2'
    allowBlobPublicAccess: false
    allowSharedKeyAccess: false
    publicNetworkAccess: 'Disabled'
  }
}

""";

    private static string GenerateVm(string name, DesignNode node, List<string> warnings)
    {
        warnings.Add($"VM '{node.Label}': Review VM size, OS disk type, and subnet assignment before deploying.");
        return $$"""
// VM: {{node.Label}}
// AVM module: br/public:avm/res/compute/virtual-machine:0.10.0
// WARNING: Review size, image, and network configuration before deployment
resource vm_{{name}} 'Microsoft.Compute/virtualMachines@2024-03-01' = {
  name: 'vm-{{name}}'
  location: location
  tags: tags
  identity: {
    type: 'SystemAssigned'  // Use managed identity, no passwords/keys
  }
  properties: {
    hardwareProfile: { vmSize: 'Standard_B2s' }  // TODO: set appropriate size
    storageProfile: {
      osDisk: { createOption: 'FromImage', managedDisk: { storageAccountType: 'Premium_LRS' } }
      imageReference: {
        publisher: 'Canonical'
        offer: '0001-com-ubuntu-server-jammy'
        sku: '22_04-lts-gen2'
        version: 'latest'
      }
    }
    networkProfile: {
      networkInterfaces: []  // TODO: reference NIC
    }
    osProfile: {
      computerName: 'vm-{{name}}'
      adminUsername: 'azureuser'
      // TODO: Use SSH public key auth or disablePasswordAuthentication: true
    }
  }
}

""";
    }

    private static string GenerateAppService(string name, DesignNode node) =>
        $$"""
// App Service: {{node.Label}}
// AVM module: br/public:avm/res/web/site:0.9.0
resource asp_{{name}} 'Microsoft.Web/serverfarms@2023-12-01' = {
  name: 'asp-{{name}}'
  location: location
  tags: tags
  sku: { name: 'P1v3', tier: 'PremiumV3' }
  properties: { reserved: true }
}

resource app_{{name}} 'Microsoft.Web/sites@2023-12-01' = {
  name: 'app-{{name}}'
  location: location
  tags: tags
  identity: { type: 'SystemAssigned' }
  properties: {
    serverFarmId: asp_{{name}}.id
    httpsOnly: true
    siteConfig: {
      ftpsState: 'Disabled'
      minTlsVersion: '1.2'
      publicNetworkAccess: 'Disabled'
    }
  }
}

""";

    private static string GeneratePrivateEndpoint(string name, DesignNode node) =>
        $$"""
// Private Endpoint: {{node.Label}}
resource pe_{{name}} 'Microsoft.Network/privateEndpoints@2024-01-01' = {
  name: 'pe-{{name}}'
  location: location
  tags: tags
  properties: {
    subnet: { id: '' }  // TODO: reference target subnet
    privateLinkServiceConnections: [
      {
        name: 'pe-{{name}}-conn'
        properties: {
          privateLinkServiceId: ''  // TODO: reference target resource
          groupIds: []              // TODO: set group ID (e.g. 'vault', 'blob', 'sqlServer')
        }
      }
    ]
  }
}

""";

    private static string GetProp(DesignNode node, string key, string defaultValue) =>
        node.Properties.TryGetValue(key, out var val) ? val?.ToString() ?? defaultValue : defaultValue;

    private static string SanitizeName(string label) =>
        new string(label.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray())
            .ToLowerInvariant()
            .TrimStart('0', '1', '2', '3', '4', '5', '6', '7', '8', '9');
}
