const ICON_BASE = '/azure-icons'

// All files are from Azure_Public_Service_Icons/Icons/** and copied to
// src/frontend/public/azure-icons so they are deployable with the SPA.
const ICONS = {
  allResources: `${ICON_BASE}/10001-icon-service-All-Resources.svg`,
  managementGroups: `${ICON_BASE}/10011-icon-service-Management-Groups.svg`,
  subscriptions: `${ICON_BASE}/10002-icon-service-Subscriptions.svg`,
  resourceGroups: `${ICON_BASE}/10007-icon-service-Resource-Groups.svg`,
  policy: `${ICON_BASE}/10316-icon-service-Policy.svg`,
  vnet: `${ICON_BASE}/10061-icon-service-Virtual-Networks.svg`,
  subnet: `${ICON_BASE}/02742-icon-service-Subnet.svg`,
  nsg: `${ICON_BASE}/10067-icon-service-Network-Security-Groups.svg`,
  routeTable: `${ICON_BASE}/10082-icon-service-Route-Tables.svg`,
  nat: `${ICON_BASE}/10310-icon-service-NAT.svg`,
  firewall: `${ICON_BASE}/10084-icon-service-Firewalls.svg`,
  vnetGateway: `${ICON_BASE}/10063-icon-service-Virtual-Network-Gateways.svg`,
  dnsZone: `${ICON_BASE}/10064-icon-service-DNS-Zones.svg`,
  privateEndpoint: `${ICON_BASE}/02579-icon-service-Private-Endpoints.svg`,
  loadBalancer: `${ICON_BASE}/10062-icon-service-Load-Balancers.svg`,
  appGateway: `${ICON_BASE}/10076-icon-service-Application-Gateways.svg`,
  virtualWan: `${ICON_BASE}/10353-icon-service-Virtual-WANs.svg`,
  virtualHub: `${ICON_BASE}/00860-icon-service-Virtual-WAN-Hub.svg`,
  bastion: `${ICON_BASE}/02422-icon-service-Bastions.svg`,
  vm: `${ICON_BASE}/10021-icon-service-Virtual-Machine.svg`,
  vmss: `${ICON_BASE}/10034-icon-service-VM-Scale-Sets.svg`,
  aks: `${ICON_BASE}/10023-icon-service-Kubernetes-Services.svg`,
  container: `${ICON_BASE}/10104-icon-service-Container-Instances.svg`,
  functionApp: `${ICON_BASE}/10029-icon-service-Function-Apps.svg`,
  appService: `${ICON_BASE}/10035-icon-service-App-Services.svg`,
  storage: `${ICON_BASE}/10086-icon-service-Storage-Accounts.svg`,
  sql: `${ICON_BASE}/10130-icon-service-SQL-Database.svg`,
  postgres: `${ICON_BASE}/10131-icon-service-Azure-Database-PostgreSQL-Server.svg`,
  cosmos: `${ICON_BASE}/10121-icon-service-Azure-Cosmos-DB.svg`,
  keyVault: `${ICON_BASE}/10245-icon-service-Key-Vaults.svg`,
  managedIdentity: `${ICON_BASE}/10227-icon-service-Managed-Identities.svg`,
  appSecurityGroup: `${ICON_BASE}/10244-icon-service-Application-Security-Groups.svg`,
  defender: `${ICON_BASE}/10241-icon-service-Microsoft-Defender-for-Cloud.svg`,
  logAnalytics: `${ICON_BASE}/00009-icon-service-Log-Analytics-Workspaces.svg`,
  internet: `${ICON_BASE}/10808-icon-service-Globe-Success.svg`,
} as const

const RESOURCE_TYPE_MAP: Record<string, string> = {
  'microsoft.resources/subscriptions': ICONS.subscriptions,
  'microsoft.resources/resourcegroups': ICONS.resourceGroups,
  'microsoft.network/virtualnetworks': ICONS.vnet,
  'microsoft.network/virtualnetworks/subnets': ICONS.subnet,
  'microsoft.network/networksecuritygroups': ICONS.nsg,
  'microsoft.network/routetables': ICONS.routeTable,
  'microsoft.network/natgateways': ICONS.nat,
  'microsoft.network/azurefirewalls': ICONS.firewall,
  'microsoft.network/virtualnetworkgateways': ICONS.vnetGateway,
  'microsoft.network/privatednszones': ICONS.dnsZone,
  'microsoft.network/privateendpoints': ICONS.privateEndpoint,
  'microsoft.network/loadbalancers': ICONS.loadBalancer,
  'microsoft.network/applicationgateways': ICONS.appGateway,
  'microsoft.network/virtualwans': ICONS.virtualWan,
  'microsoft.network/virtualhubs': ICONS.virtualHub,
  'microsoft.compute/virtualmachines': ICONS.vm,
  'microsoft.compute/virtualmachinescalesets': ICONS.vmss,
  'microsoft.containerservice/managedclusters': ICONS.aks,
  'microsoft.app/containerapps': ICONS.container,
  'microsoft.web/sites': ICONS.appService,
  'microsoft.storage/storageaccounts': ICONS.storage,
  'microsoft.sql/servers/databases': ICONS.sql,
  'microsoft.dbforpostgresql/flexibleservers': ICONS.postgres,
  'microsoft.documentdb/databaseaccounts': ICONS.cosmos,
  'microsoft.keyvault/vaults': ICONS.keyVault,
  'microsoft.managedidentity/userassignedidentities': ICONS.managedIdentity,
  'microsoft.operationalinsights/workspaces': ICONS.logAnalytics,
  'easyazure.network/internet': ICONS.internet,
}

const BLOCK_TYPE_MAP: Record<string, string> = {
  'Management Group': ICONS.managementGroups,
  Subscription: ICONS.subscriptions,
  'Resource Group': ICONS.resourceGroups,
  'Policy Assignment': ICONS.policy,
  VNet: ICONS.vnet,
  Subnet: ICONS.subnet,
  NSG: ICONS.nsg,
  'Route Table': ICONS.routeTable,
  'NAT Gateway': ICONS.nat,
  'Azure Firewall': ICONS.firewall,
  'VPN Gateway': ICONS.vnetGateway,
  'ExpressRoute Gateway': ICONS.vnetGateway,
  'Private DNS Zone': ICONS.dnsZone,
  'Private Endpoint': ICONS.privateEndpoint,
  'Load Balancer': ICONS.loadBalancer,
  'Application Gateway': ICONS.appGateway,
  'Virtual WAN': ICONS.virtualWan,
  'Virtual Hub': ICONS.virtualHub,
  VM: ICONS.vm,
  'VM Scale Set': ICONS.vmss,
  AKS: ICONS.aks,
  'Container App': ICONS.container,
  'Function App': ICONS.functionApp,
  'App Service': ICONS.appService,
  'Storage Account': ICONS.storage,
  'SQL Database': ICONS.sql,
  PostgreSQL: ICONS.postgres,
  'Cosmos DB': ICONS.cosmos,
  'Key Vault': ICONS.keyVault,
  'Managed Identity': ICONS.managedIdentity,
  'RBAC Assignment': ICONS.appSecurityGroup,
  'Defender for Cloud': ICONS.defender,
  Bastion: ICONS.bastion,
  'Log Analytics': ICONS.logAnalytics,
  'Hub-spoke network': ICONS.virtualWan,
  'App landing zone': ICONS.resourceGroups,
  'Secure web app': ICONS.appGateway,
  'Private app service': ICONS.privateEndpoint,
  'AKS baseline': ICONS.aks,
  'Three-tier app': ICONS.allResources,
}

export function getAzureIconForResourceType(type: string): string {
  const lower = type.toLowerCase()
  return RESOURCE_TYPE_MAP[lower] ?? ICONS.allResources
}

export function getAzureIconForBlockType(blockType: string): string {
  return BLOCK_TYPE_MAP[blockType] ?? ICONS.allResources
}
